### ISSUE TITLE
Process substitution with bash 5.2.0 (Build 551)

### ISSUE THREAD

**Issue by gngrossi** [ZOSOpenTools/bashport#49]
# bash 5.2.0 (Build 551) (bash-5.2.20230215_173052.zos.pax.Z)
# look like process substitution is not yielding proper results

RC=(0) [SYSD] bash-5.2$ echo <(date)
/u/@02858/tmp/sh-np.DhdCxQ

RC=(0) [SYSD] bash-5.2$ cat <(date)
▒▒̀▒▒�▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒RC=(0) [SYSD] bash-5.2$

RC=(0) [SYSD] bash-5.2$ wc -l <(ssh l98misdb491 "cat *Yum")
      0    /u/@02858/tmp/sh-np.gbAaxQ

--

# Expecting something like this

$ echo <(date)
/dev/fd63

$ cat <(date)
Thu Feb 16 13:29:25 CST 2023

$ wc -l <(ssh l98misdb491 "cat *Yum")
      4    /dev/fd63

**Comment by gngrossi** [comment]
GNU bash, version 5.2.0(1)-release (i370-ibm-openedition)

RC=(0) [SYSA] bash-5.2$ cat <(date) | xxd
00000000: e8cd c180 282f ca80 9194 8091 969a 9590  ▒▒▒..ʀ▒▒▒▒▒▒▒▒
00000010: 9a90 9180 e4e0 e880 1690 1693 8e         ▒▒▒▒▒▒▒.▒.▒▒

RC=(0) [SYSA] bash-5.2$ cat <(date) | od -hc
0000000000    E8  CD  C1  80  28  2F  CA  80  91  94  80  91  96  9A  95  90
               Y 315   A 200 050  \a 312 200   j   m 200   j   o 232   n 220
0000000020    9A  90  04  80  E4  E0  E8  80  16  90  16  93  8E
             232 220 004 200   U   \   Y 200  \b 220  \b   l 216
0000000035

**Comment by gngrossi** [comment]
bashport_768/bash-5.2.20230319_200518.zos.pax.Z

# This is now working as expected
bash-5.2$ cat <(date)
Mon Mar 20 18:18:27 CDT 2023

# Is this working as expected?  Should there be a /dev/fdxx returned?
bash-5.2$ echo <(date)
/u/@02858/tmp/sh-np.CechxQ

# Getting the correct line count. Should there be a /dev/fdxx returned?
bash-5.2$ wc -l <(ssh l98misdb491 "cat *Yum")
4 /u/@02858/tmp/sh-np.AEBbxQ

**Comment by IgorTodorovskiIBM** [comment]
I think there's two things going on here.
1. It appears that our CI machines are not consistently setting HAVE_DEV_FD, not setting this triggers an alternate path to be used which create temporary files using mktemps. This is determine by the check `test -r /dev/fd/0` which returns 0 on some of our CI machines and 1 on others.
2. zoslib does not appear to handle untagged character devices properly, such as /dev/fd*. I'll look into this

**Comment by gngrossi** [comment]
bash-5.2$ bash --version | head -n1
GNU bash, version 5.2.15(1)-release (i370-ibm-openedition)

bash-5.2$ cat <(date)
cat: /dev/fd/63: EDC5135I Not a directory.

# looks good
bash-5.2$ echo <(date)
/dev/fd/63

bash-5.2$ wc -l <(ssh l98misdb491 "cat *Yum")
wc: /dev/fd/63: EDC5135I Not a directory.

**Comment by IgorTodorovskiIBM** [comment]
We noticed there's an inconsistency on some of our z/OS machines `/dev/fd` is a character device and not a directory. So we made a change to use FIFO special files and to also tag them as such:
```
[ITODORO@ZOSCAN2B ~/zopen/prod/bash/bin]$  ls -lT <(date)
t ISO8859-1   T=on  prw-------   1 ITODORO  SUDOGRP        0 Mar 24 11:28 /tmp/sh-np.ghEFxQ
[ITODORO@ZOSCAN2B ~/zopen/prod/bash/bin]$ /home/itodoro/zopen/prod/coreutils/bin/cat <(date)
Fri Mar 24 11:28:48 EDT 2023
[ITODORO@ZOSCAN2B ~/zopen/prod/bash/bin]$ /bin/cat  <(date)
Fri Mar 24 11:28:55 EDT 2023
```

**Comment by gngrossi** [comment]
Are these the final results to be expected?  If so, I will close. 
thanks

bash 5.2.15 (Build 799)

RC=(0) [SYSA] bash-5.2$ cat <(date)
Fri Mar 24 11:34:28 CDT 2023

RC=(0) [SYSA] bash-5.2$ echo <(date)
/u/@02858/tmp/sh-np.hcabxQ

RC=(0) [SYSA] bash-5.2$ wc -l <(ssh l98misdb491 "cat *Yum")
4 /u/@02858/tmp/sh-np.GAfdxQ

**Comment by IgorTodorovskiIBM** [comment]
Yes, for now at least. At some point I'll revisit the /dev/fd issue as it may result in better performance. Opened issue https://github.com/ZOSOpenTools/bashport/issues/59
