### ISSUE TITLE
bash <() seems to treat data as 1047

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/bashport#5]
In the bash shell, run the following using the 'coreutils' diff (which has the -u capability)

```
echo "Hello" >hw.txt
diff -u <(sed -e 's/H/J/' hw.txt) <(cat hw.txt)
--- /tmp/sh-np.ddhFxQ	2022-11-25 18:33:28 +0000
+++ /tmp/sh-np.haaHxQ	2022-11-25 18:33:28 +0000
@@ -1 +1 @@
-х���
\ No newline at end of file
+ȅ���
\ No newline at end of file
```

Compare this to running with the 'standard' /bin/diff and you get:
```
/bin/diff <(sed -e 's/H/J/' hw.txt) <(cat hw.txt)
1c1
< Jello
---
> Hello
```

which could indicate the temp files are both untagged (and treated as 1047)

**Comment by MikeFultonDev** [comment]
This shows up in the top-level Makefile for gnulib port:

```
sc_check_sym_list:
  @i=lib/intprops.h; \
  diff -u <(perl -lne '/^# *define ([A-Z]\w+)\(/ and print $$1' $$i|fmt) \
    <(sed -n /^_intprops_name/,/^_intprops_syms_re/p top/maint.mk \
      |sed '/^_/d;s/^  //;s/  *\\$$//')
```

**Comment by IgorTodorovskiIBM** [comment]
It seems that the temporary file is untagged:
```
- untagged    T=off prw-------   1 ITODORO  SUDOGRP        0 Nov 25 22:52 /tmp/sh-np.DEcexQ
```
With Rocket bash it's tagged as ISO8859-1.

I'm rebuilding locally with the latest zoslib to see if that helps.

**Comment by IgorTodorovskiIBM** [comment]
Looks like mkfifo is the culprit, another one to add to the list of overrides

**Comment by MikeFultonDev** [comment]
@IgorTodorovskiIBM did you tackle this yet?

**Comment by IgorTodorovskiIBM** [comment]
Yep, we can close this off, handled under https://github.com/ZOSOpenTools/bashport/commit/0d29564f19290ab93031e1e1d2d25515f152a11e
