### ISSUE TITLE
netstat not found from the bash shell

### ISSUE THREAD

**Issue by gngrossi** [ZOSOpenTools/bashport#50]
Is this expected running bash?   Does bash honor _BPX_SHAREAS=YES ?

bash-5.2$ type netstat
bash: type: netstat: not found

bash-5.2$ whence netstat
bash: whence: command not found

bash-5.2$ which netstat
bash: which: command not found

bash-5.2$ netstat
bash: netstat: command not found

bash-5.2$ type onetstat
onetstat is hashed (/bin/onetstat)

links in /bin
bash-5.2$ cd /bin
erwxrwxrwx   1 BPXROOT  10             8 Oct 12  2021 netstat -> ONETSTAT
lrwxrwxrwx   1 BPXROOT  10            29 Oct 12  2021 onetstat -> ../usr/lpp/tcpip/bin/onetstat

**Comment by IgorTodorovskiIBM** [comment]
This is fixed in the latest release - https://github.com/ZOSOpenTools/bashport/releases/tag/bashport_793
```
[ITODORO@ZOSCAN2B ~/zopen/prod/bash]$ type netstat
netstat is /bin/netstat
[ITODORO@ZOSCAN2B ~/zopen/prod/bash]$ netstat
MVS TCP/IP NETSTAT CS V2R4       TCPIP Name: TCPIP           12:32:57
User Id  Conn     State
-------  ----     -----
BPXOINIT 0000006C Listen
  Local Socket:   0.0.0.0..10007
  Foreign Socket: 0.0.0.0..0
DB2CDIST 000000B8 Listen
  Local Socket:   ::..7502
  Foreign Socket: ::..0
```

**Comment by gngrossi** [comment]
bash updated and tested successfully
thanks
